//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAFixture_WebApplication.WCFService_225 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Connectdatabase2")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFService_225.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        MAFixture_WebApplication.WCFService_225.CompositeType GetDataUsingDataContract(MAFixture_WebApplication.WCFService_225.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<MAFixture_WebApplication.WCFService_225.CompositeType> GetDataUsingDataContractAsync(MAFixture_WebApplication.WCFService_225.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetConnectMAFixture", ReplyAction="http://tempuri.org/IService1/GetConnectMAFixtureResponse")]
        string GetConnectMAFixture();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetConnectMAFixture", ReplyAction="http://tempuri.org/IService1/GetConnectMAFixtureResponse")]
        System.Threading.Tasks.Task<string> GetConnectMAFixtureAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectAOIHM", ReplyAction="http://tempuri.org/IService1/ConnectAOIHMResponse")]
        string ConnectAOIHM();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectAOIHM", ReplyAction="http://tempuri.org/IService1/ConnectAOIHMResponse")]
        System.Threading.Tasks.Task<string> ConnectAOIHMAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectPackingmaterial", ReplyAction="http://tempuri.org/IService1/ConnectPackingmaterialResponse")]
        string ConnectPackingmaterial();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectPackingmaterial", ReplyAction="http://tempuri.org/IService1/ConnectPackingmaterialResponse")]
        System.Threading.Tasks.Task<string> ConnectPackingmaterialAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectMinitabGenerator", ReplyAction="http://tempuri.org/IService1/ConnectMinitabGeneratorResponse")]
        string ConnectMinitabGenerator();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectMinitabGenerator", ReplyAction="http://tempuri.org/IService1/ConnectMinitabGeneratorResponse")]
        System.Threading.Tasks.Task<string> ConnectMinitabGeneratorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectMon_program", ReplyAction="http://tempuri.org/IService1/ConnectMon_programResponse")]
        string ConnectMon_program();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectMon_program", ReplyAction="http://tempuri.org/IService1/ConnectMon_programResponse")]
        System.Threading.Tasks.Task<string> ConnectMon_programAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectGrundfosTest", ReplyAction="http://tempuri.org/IService1/ConnectGrundfosTestResponse")]
        string ConnectGrundfosTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectGrundfosTest", ReplyAction="http://tempuri.org/IService1/ConnectGrundfosTestResponse")]
        System.Threading.Tasks.Task<string> ConnectGrundfosTestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectDanelecPTS", ReplyAction="http://tempuri.org/IService1/ConnectDanelecPTSResponse")]
        string ConnectDanelecPTS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectDanelecPTS", ReplyAction="http://tempuri.org/IService1/ConnectDanelecPTSResponse")]
        System.Threading.Tasks.Task<string> ConnectDanelecPTSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectMechanic", ReplyAction="http://tempuri.org/IService1/ConnectMechanicResponse")]
        string ConnectMechanic();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectMechanic", ReplyAction="http://tempuri.org/IService1/ConnectMechanicResponse")]
        System.Threading.Tasks.Task<string> ConnectMechanicAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSMTAOI", ReplyAction="http://tempuri.org/IService1/ConnectSMTAOIResponse")]
        string ConnectSMTAOI();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSMTAOI", ReplyAction="http://tempuri.org/IService1/ConnectSMTAOIResponse")]
        System.Threading.Tasks.Task<string> ConnectSMTAOIAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSMTAOIREPORT", ReplyAction="http://tempuri.org/IService1/ConnectSMTAOIREPORTResponse")]
        string ConnectSMTAOIREPORT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSMTAOIREPORT", ReplyAction="http://tempuri.org/IService1/ConnectSMTAOIREPORTResponse")]
        System.Threading.Tasks.Task<string> ConnectSMTAOIREPORTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSMTSchedule", ReplyAction="http://tempuri.org/IService1/ConnectSMTScheduleResponse")]
        string ConnectSMTSchedule();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSMTSchedule", ReplyAction="http://tempuri.org/IService1/ConnectSMTScheduleResponse")]
        System.Threading.Tasks.Task<string> ConnectSMTScheduleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSmartDigital", ReplyAction="http://tempuri.org/IService1/ConnectSmartDigitalResponse")]
        string ConnectSmartDigital();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSmartDigital", ReplyAction="http://tempuri.org/IService1/ConnectSmartDigitalResponse")]
        System.Threading.Tasks.Task<string> ConnectSmartDigitalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectTestLogOnBase", ReplyAction="http://tempuri.org/IService1/ConnectTestLogOnBaseResponse")]
        string ConnectTestLogOnBase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectTestLogOnBase", ReplyAction="http://tempuri.org/IService1/ConnectTestLogOnBaseResponse")]
        System.Threading.Tasks.Task<string> ConnectTestLogOnBaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSTMPTS", ReplyAction="http://tempuri.org/IService1/ConnectSTMPTSResponse")]
        string ConnectSTMPTS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSTMPTS", ReplyAction="http://tempuri.org/IService1/ConnectSTMPTSResponse")]
        System.Threading.Tasks.Task<string> ConnectSTMPTSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectPTS_HM", ReplyAction="http://tempuri.org/IService1/ConnectPTS_HMResponse")]
        string ConnectPTS_HM();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectPTS_HM", ReplyAction="http://tempuri.org/IService1/ConnectPTS_HMResponse")]
        System.Threading.Tasks.Task<string> ConnectPTS_HMAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectAOIInspection", ReplyAction="http://tempuri.org/IService1/ConnectAOIInspectionResponse")]
        string ConnectAOIInspection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectAOIInspection", ReplyAction="http://tempuri.org/IService1/ConnectAOIInspectionResponse")]
        System.Threading.Tasks.Task<string> ConnectAOIInspectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectOven", ReplyAction="http://tempuri.org/IService1/ConnectOvenResponse")]
        string ConnectOven();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectOven", ReplyAction="http://tempuri.org/IService1/ConnectOvenResponse")]
        System.Threading.Tasks.Task<string> ConnectOvenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectComet", ReplyAction="http://tempuri.org/IService1/ConnectCometResponse")]
        string ConnectComet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectComet", ReplyAction="http://tempuri.org/IService1/ConnectCometResponse")]
        System.Threading.Tasks.Task<string> ConnectCometAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectRecom", ReplyAction="http://tempuri.org/IService1/ConnectRecomResponse")]
        string ConnectRecom();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectRecom", ReplyAction="http://tempuri.org/IService1/ConnectRecomResponse")]
        System.Threading.Tasks.Task<string> ConnectRecomAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectLaserMarkDanfoss", ReplyAction="http://tempuri.org/IService1/ConnectLaserMarkDanfossResponse")]
        string ConnectLaserMarkDanfoss();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectLaserMarkDanfoss", ReplyAction="http://tempuri.org/IService1/ConnectLaserMarkDanfossResponse")]
        System.Threading.Tasks.Task<string> ConnectLaserMarkDanfossAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectHoneywell", ReplyAction="http://tempuri.org/IService1/ConnectHoneywellResponse")]
        string ConnectHoneywell();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectHoneywell", ReplyAction="http://tempuri.org/IService1/ConnectHoneywellResponse")]
        System.Threading.Tasks.Task<string> ConnectHoneywellAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectRotork", ReplyAction="http://tempuri.org/IService1/ConnectRotorkResponse")]
        string ConnectRotork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectRotork", ReplyAction="http://tempuri.org/IService1/ConnectRotorkResponse")]
        System.Threading.Tasks.Task<string> ConnectRotorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectILoq", ReplyAction="http://tempuri.org/IService1/ConnectILoqResponse")]
        string ConnectILoq();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectILoq", ReplyAction="http://tempuri.org/IService1/ConnectILoqResponse")]
        System.Threading.Tasks.Task<string> ConnectILoqAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectRD_MES", ReplyAction="http://tempuri.org/IService1/ConnectRD_MESResponse")]
        string ConnectRD_MES();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectRD_MES", ReplyAction="http://tempuri.org/IService1/ConnectRD_MESResponse")]
        System.Threading.Tasks.Task<string> ConnectRD_MESAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSSM", ReplyAction="http://tempuri.org/IService1/ConnectSSMResponse")]
        string ConnectSSM();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSSM", ReplyAction="http://tempuri.org/IService1/ConnectSSMResponse")]
        System.Threading.Tasks.Task<string> ConnectSSMAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectABB", ReplyAction="http://tempuri.org/IService1/ConnectABBResponse")]
        string ConnectABB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectABB", ReplyAction="http://tempuri.org/IService1/ConnectABBResponse")]
        System.Threading.Tasks.Task<string> ConnectABBAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectNordson", ReplyAction="http://tempuri.org/IService1/ConnectNordsonResponse")]
        string ConnectNordson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectNordson", ReplyAction="http://tempuri.org/IService1/ConnectNordsonResponse")]
        System.Threading.Tasks.Task<string> ConnectNordsonAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MAFixture_WebApplication.WCFService_225.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MAFixture_WebApplication.WCFService_225.IService1>, MAFixture_WebApplication.WCFService_225.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public MAFixture_WebApplication.WCFService_225.CompositeType GetDataUsingDataContract(MAFixture_WebApplication.WCFService_225.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<MAFixture_WebApplication.WCFService_225.CompositeType> GetDataUsingDataContractAsync(MAFixture_WebApplication.WCFService_225.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string GetConnectMAFixture() {
            return base.Channel.GetConnectMAFixture();
        }
        
        public System.Threading.Tasks.Task<string> GetConnectMAFixtureAsync() {
            return base.Channel.GetConnectMAFixtureAsync();
        }
        
        public string ConnectAOIHM() {
            return base.Channel.ConnectAOIHM();
        }
        
        public System.Threading.Tasks.Task<string> ConnectAOIHMAsync() {
            return base.Channel.ConnectAOIHMAsync();
        }
        
        public string ConnectPackingmaterial() {
            return base.Channel.ConnectPackingmaterial();
        }
        
        public System.Threading.Tasks.Task<string> ConnectPackingmaterialAsync() {
            return base.Channel.ConnectPackingmaterialAsync();
        }
        
        public string ConnectMinitabGenerator() {
            return base.Channel.ConnectMinitabGenerator();
        }
        
        public System.Threading.Tasks.Task<string> ConnectMinitabGeneratorAsync() {
            return base.Channel.ConnectMinitabGeneratorAsync();
        }
        
        public string ConnectMon_program() {
            return base.Channel.ConnectMon_program();
        }
        
        public System.Threading.Tasks.Task<string> ConnectMon_programAsync() {
            return base.Channel.ConnectMon_programAsync();
        }
        
        public string ConnectGrundfosTest() {
            return base.Channel.ConnectGrundfosTest();
        }
        
        public System.Threading.Tasks.Task<string> ConnectGrundfosTestAsync() {
            return base.Channel.ConnectGrundfosTestAsync();
        }
        
        public string ConnectDanelecPTS() {
            return base.Channel.ConnectDanelecPTS();
        }
        
        public System.Threading.Tasks.Task<string> ConnectDanelecPTSAsync() {
            return base.Channel.ConnectDanelecPTSAsync();
        }
        
        public string ConnectMechanic() {
            return base.Channel.ConnectMechanic();
        }
        
        public System.Threading.Tasks.Task<string> ConnectMechanicAsync() {
            return base.Channel.ConnectMechanicAsync();
        }
        
        public string ConnectSMTAOI() {
            return base.Channel.ConnectSMTAOI();
        }
        
        public System.Threading.Tasks.Task<string> ConnectSMTAOIAsync() {
            return base.Channel.ConnectSMTAOIAsync();
        }
        
        public string ConnectSMTAOIREPORT() {
            return base.Channel.ConnectSMTAOIREPORT();
        }
        
        public System.Threading.Tasks.Task<string> ConnectSMTAOIREPORTAsync() {
            return base.Channel.ConnectSMTAOIREPORTAsync();
        }
        
        public string ConnectSMTSchedule() {
            return base.Channel.ConnectSMTSchedule();
        }
        
        public System.Threading.Tasks.Task<string> ConnectSMTScheduleAsync() {
            return base.Channel.ConnectSMTScheduleAsync();
        }
        
        public string ConnectSmartDigital() {
            return base.Channel.ConnectSmartDigital();
        }
        
        public System.Threading.Tasks.Task<string> ConnectSmartDigitalAsync() {
            return base.Channel.ConnectSmartDigitalAsync();
        }
        
        public string ConnectTestLogOnBase() {
            return base.Channel.ConnectTestLogOnBase();
        }
        
        public System.Threading.Tasks.Task<string> ConnectTestLogOnBaseAsync() {
            return base.Channel.ConnectTestLogOnBaseAsync();
        }
        
        public string ConnectSTMPTS() {
            return base.Channel.ConnectSTMPTS();
        }
        
        public System.Threading.Tasks.Task<string> ConnectSTMPTSAsync() {
            return base.Channel.ConnectSTMPTSAsync();
        }
        
        public string ConnectPTS_HM() {
            return base.Channel.ConnectPTS_HM();
        }
        
        public System.Threading.Tasks.Task<string> ConnectPTS_HMAsync() {
            return base.Channel.ConnectPTS_HMAsync();
        }
        
        public string ConnectAOIInspection() {
            return base.Channel.ConnectAOIInspection();
        }
        
        public System.Threading.Tasks.Task<string> ConnectAOIInspectionAsync() {
            return base.Channel.ConnectAOIInspectionAsync();
        }
        
        public string ConnectOven() {
            return base.Channel.ConnectOven();
        }
        
        public System.Threading.Tasks.Task<string> ConnectOvenAsync() {
            return base.Channel.ConnectOvenAsync();
        }
        
        public string ConnectComet() {
            return base.Channel.ConnectComet();
        }
        
        public System.Threading.Tasks.Task<string> ConnectCometAsync() {
            return base.Channel.ConnectCometAsync();
        }
        
        public string ConnectRecom() {
            return base.Channel.ConnectRecom();
        }
        
        public System.Threading.Tasks.Task<string> ConnectRecomAsync() {
            return base.Channel.ConnectRecomAsync();
        }
        
        public string ConnectLaserMarkDanfoss() {
            return base.Channel.ConnectLaserMarkDanfoss();
        }
        
        public System.Threading.Tasks.Task<string> ConnectLaserMarkDanfossAsync() {
            return base.Channel.ConnectLaserMarkDanfossAsync();
        }
        
        public string ConnectHoneywell() {
            return base.Channel.ConnectHoneywell();
        }
        
        public System.Threading.Tasks.Task<string> ConnectHoneywellAsync() {
            return base.Channel.ConnectHoneywellAsync();
        }
        
        public string ConnectRotork() {
            return base.Channel.ConnectRotork();
        }
        
        public System.Threading.Tasks.Task<string> ConnectRotorkAsync() {
            return base.Channel.ConnectRotorkAsync();
        }
        
        public string ConnectILoq() {
            return base.Channel.ConnectILoq();
        }
        
        public System.Threading.Tasks.Task<string> ConnectILoqAsync() {
            return base.Channel.ConnectILoqAsync();
        }
        
        public string ConnectRD_MES() {
            return base.Channel.ConnectRD_MES();
        }
        
        public System.Threading.Tasks.Task<string> ConnectRD_MESAsync() {
            return base.Channel.ConnectRD_MESAsync();
        }
        
        public string ConnectSSM() {
            return base.Channel.ConnectSSM();
        }
        
        public System.Threading.Tasks.Task<string> ConnectSSMAsync() {
            return base.Channel.ConnectSSMAsync();
        }
        
        public string ConnectABB() {
            return base.Channel.ConnectABB();
        }
        
        public System.Threading.Tasks.Task<string> ConnectABBAsync() {
            return base.Channel.ConnectABBAsync();
        }
        
        public string ConnectNordson() {
            return base.Channel.ConnectNordson();
        }
        
        public System.Threading.Tasks.Task<string> ConnectNordsonAsync() {
            return base.Channel.ConnectNordsonAsync();
        }
    }
}
