//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAFixture_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.MAPlans = new HashSet<MAPlan>();
        }
    
        public long ID { get; set; }
        public string Cust_name { get; set; }
        public string Cust_codename { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Createby { get; set; }
    
        public virtual ICollection<MAPlan> MAPlans { get; set; }
    }
}
