//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAFixture_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilesMA
    {
        public FilesMA()
        {
            this.MAChecklistdetails = new HashSet<MAChecklistdetail>();
            this.ImageAfters = new HashSet<ImageAfter>();
            this.ImageBefores = new HashSet<ImageBefore>();
        }
    
        public long ID { get; set; }
        public long MA_ID { get; set; }
        public string Name { get; set; }
        public byte[] File { get; set; }
        public System.DateTime Createdate { get; set; }
        public string PlanName { get; set; }
        public string Format { get; set; }
        public string FilenameBefore { get; set; }
        public string FilenameAfter { get; set; }
        public string Createby { get; set; }
        public Nullable<System.DateTime> Insertdate { get; set; }
        public string Serial_No { get; set; }
        public string MA_Status { get; set; }
        public string GradeBefore { get; set; }
        public string GradeAfter { get; set; }
        public string Comment { get; set; }
    
        public virtual MAPlan MAPlan { get; set; }
        public virtual ICollection<MAChecklistdetail> MAChecklistdetails { get; set; }
        public virtual ICollection<ImageAfter> ImageAfters { get; set; }
        public virtual ICollection<ImageBefore> ImageBefores { get; set; }
    }
}
