//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAFixture_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupEmail
    {
        public GroupEmail()
        {
            this.MAPlans = new HashSet<MAPlan>();
        }
    
        public long ID { get; set; }
        public string MailTo { get; set; }
        public string MailCC { get; set; }
        public string Section { get; set; }
        public string Prefix { get; set; }
        public string Acknowledge_Overdue { get; set; }
    
        public virtual ICollection<MAPlan> MAPlans { get; set; }
    }
}
