//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAFixture_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageBefore
    {
        public long ID { get; set; }
        public string Image_Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> FilesMA_ID { get; set; }
    
        public virtual FilesMA FilesMA { get; set; }
    }
}
