//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAFixture_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAChecklistdetail
    {
        public long ID { get; set; }
        public Nullable<long> FID { get; set; }
        public string Checklistdetail { get; set; }
        public string Status { get; set; }
        public string Problem { get; set; }
        public string Remark { get; set; }
    
        public virtual FilesMA FilesMA { get; set; }
    }
}
