//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAFixture_WebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MAFixtureEntities : DbContext
    {
        public MAFixtureEntities()
            : base("name=MAFixtureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<FilesMA> FilesMAs { get; set; }
        public virtual DbSet<GroupEmail> GroupEmails { get; set; }
        public virtual DbSet<MAChecklistdetail> MAChecklistdetails { get; set; }
        public virtual DbSet<MAPlan> MAPlans { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_MasterMATester> Tbl_MasterMATester { get; set; }
        public virtual DbSet<ImageAfter> ImageAfters { get; set; }
        public virtual DbSet<ImageBefore> ImageBefores { get; set; }
        public virtual DbSet<Tbl_Pindetail> Tbl_Pindetail { get; set; }
        public virtual DbSet<Machine> Machines { get; set; }
        public virtual DbSet<Tbl_KPIoverdue> Tbl_KPIoverdue { get; set; }
    }
}
