//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAFixture_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAPlan
    {
        public MAPlan()
        {
            this.FilesMAs = new HashSet<FilesMA>();
            this.Tbl_ProductName = new HashSet<Tbl_ProductName>();
        }
    
        public long MA_ID { get; set; }
        public string Equipment_No { get; set; }
        public string Equipment_Name { get; set; }
        public string Product_name { get; set; }
        public string Type_MC { get; set; }
        public string Model { get; set; }
        public string Serial_No { get; set; }
        public string Property { get; set; }
        public string Referrence_No { get; set; }
        public string Responsible_Name { get; set; }
        public string Manufacture { get; set; }
        public string Description { get; set; }
        public System.DateTime LastMA_date { get; set; }
        public long GE_ID { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public string Section { get; set; }
        public Nullable<long> Customer { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<System.DateTime> Plan_Daily { get; set; }
        public Nullable<System.DateTime> Plan_Weekly { get; set; }
        public Nullable<System.DateTime> Plan_Monthly { get; set; }
        public Nullable<System.DateTime> Plan_Semi_annually { get; set; }
        public Nullable<System.DateTime> Plan_Quarterly { get; set; }
        public Nullable<System.DateTime> Plan_Yearly { get; set; }
        public Nullable<byte> StatusF { get; set; }
        public string Pinnumber { get; set; }
        public string Lifetime { get; set; }
        public string Location { get; set; }
        public Nullable<long> P_ID { get; set; }
        public string Type_MA { get; set; }
        public Nullable<System.DateTime> Plan_Manually { get; set; }
        public string GPVProcess { get; set; }
        public string ProcessSide { get; set; }
        public string WithTopCover { get; set; }
        public string WithControlTooling { get; set; }
        public string Grade_Status { get; set; }
        public string Dimension { get; set; }
        public string Equipment_Picture { get; set; }
        public string Type_Tools { get; set; }
        public string Modifyby { get; set; }
        public Nullable<System.DateTime> Modifydate { get; set; }
    
        public virtual Customer Customer1 { get; set; }
        public virtual ICollection<FilesMA> FilesMAs { get; set; }
        public virtual GroupEmail GroupEmail { get; set; }
        public virtual Tbl_Pindetail Tbl_Pindetail { get; set; }
        public virtual ICollection<Tbl_ProductName> Tbl_ProductName { get; set; }
    }
}
