//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAFixture_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Pindetail
    {
        public Tbl_Pindetail()
        {
            this.MAPlans = new HashSet<MAPlan>();
        }
    
        public long ID { get; set; }
        public string Pinnumber { get; set; }
        public string Product { get; set; }
        public string Lifetime { get; set; }
        public string Pinname { get; set; }
    
        public virtual ICollection<MAPlan> MAPlans { get; set; }
    }
}
