//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAFixture_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_KPIoverdue
    {
        public long ID { get; set; }
        public string Department { get; set; }
        public Nullable<int> WorkWeek { get; set; }
        public Nullable<int> QtyEquipment { get; set; }
        public Nullable<int> QtyTools { get; set; }
        public string Year { get; set; }
    }
}
