//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAFixture_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_LogMasterTools
    {
        public int ID { get; set; }
        public Nullable<int> MT_ID { get; set; }
        public Nullable<double> Cycle_Time { get; set; }
        public string Updateby { get; set; }
        public Nullable<System.DateTime> Updatedate { get; set; }
        public string Update_Comment { get; set; }
        public string Update_Log { get; set; }
    }
}
