//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAFixture_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MasterTools
    {
        public int ID { get; set; }
        public string Product_name { get; set; }
        public string Section { get; set; }
        public string Type { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Status { get; set; }
        public string Createby { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
    }
}
