//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAFixture_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Summarize_Tools
    {
        public Tbl_Summarize_Tools()
        {
            this.Tbl_ProductName = new HashSet<Tbl_ProductName>();
        }
    
        public int ID { get; set; }
        public string Product_name { get; set; }
        public string Section { get; set; }
        public string Type { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> Last_Update { get; set; }
    
        public virtual ICollection<Tbl_ProductName> Tbl_ProductName { get; set; }
    }
}
