//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAFixture_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ProductName
    {
        public int ID { get; set; }
        public Nullable<long> MA_ID { get; set; }
        public Nullable<int> S_ID { get; set; }
        public string Product_name { get; set; }
    
        public virtual MAPlan MAPlan { get; set; }
        public virtual Tbl_Summarize_Tools Tbl_Summarize_Tools { get; set; }
    }
}
