//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAFixture_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MasterMATester
    {
        public int ID { get; set; }
        public string DetailEng { get; set; }
        public string DetailThai { get; set; }
        public string Category { get; set; }
        public string Section { get; set; }
        public string Machinename { get; set; }
        public string Type_MA { get; set; }
        public string Createby { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string Updateby { get; set; }
        public Nullable<System.DateTime> Updatedate { get; set; }
        public string Status { get; set; }
    }
}
