//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAFixture_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_employee
    {
        public long ID { get; set; }
        public string EmpID { get; set; }
        public string Name { get; set; }
        public string KeyID { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string Createby { get; set; }
        public string Depart { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Status { get; set; }
        public string Accountname { get; set; }
        public string Email { get; set; }
        public string Staus_trainingOJT { get; set; }
        public string GPV_Sitename { get; set; }
        public string Status_SafetyTraining { get; set; }
    }
}
