//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAFixture_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WIP_status
    {
        public long WID { get; set; }
        public string Workorder { get; set; }
        public string Drawing { get; set; }
        public int StartesQTY { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ScheduledEnd { get; set; }
        public string Operation { get; set; }
        public int GoodQTY { get; set; }
        public Nullable<int> ErrorQTY { get; set; }
        public string SettledWith { get; set; }
        public string Reference { get; set; }
        public string Customer { get; set; }
        public string Latestdate { get; set; }
        public string Latesttime { get; set; }
        public Nullable<int> Operation_num { get; set; }
        public string Work_centre { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateFile { get; set; }
        public string Status_Close { get; set; }
        public string Status_modify { get; set; }
        public string BOMnumber { get; set; }
    
        public virtual WIP_status WIP_status1 { get; set; }
        public virtual WIP_status WIP_status2 { get; set; }
    }
}
