//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAFixture_WebApplication.WCF227Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Connectdatabase")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF227Service.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectBOM_Checking", ReplyAction="http://tempuri.org/IService1/ConnectBOM_CheckingResponse")]
        string ConnectBOM_Checking();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectBOM_Checking", ReplyAction="http://tempuri.org/IService1/ConnectBOM_CheckingResponse")]
        System.Threading.Tasks.Task<string> ConnectBOM_CheckingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSTM", ReplyAction="http://tempuri.org/IService1/ConnectSTMResponse")]
        string ConnectSTM();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSTM", ReplyAction="http://tempuri.org/IService1/ConnectSTMResponse")]
        System.Threading.Tasks.Task<string> ConnectSTMAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Microscan_new", ReplyAction="http://tempuri.org/IService1/Microscan_newResponse")]
        string Microscan_new();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Microscan_new", ReplyAction="http://tempuri.org/IService1/Microscan_newResponse")]
        System.Threading.Tasks.Task<string> Microscan_newAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Grundfos_pr", ReplyAction="http://tempuri.org/IService1/Grundfos_prResponse")]
        string Grundfos_pr();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Grundfos_pr", ReplyAction="http://tempuri.org/IService1/Grundfos_prResponse")]
        System.Threading.Tasks.Task<string> Grundfos_prAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectGNO", ReplyAction="http://tempuri.org/IService1/ConnectGNOResponse")]
        string ConnectGNO();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectGNO", ReplyAction="http://tempuri.org/IService1/ConnectGNOResponse")]
        System.Threading.Tasks.Task<string> ConnectGNOAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectFoss", ReplyAction="http://tempuri.org/IService1/ConnectFossResponse")]
        string ConnectFoss();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectFoss", ReplyAction="http://tempuri.org/IService1/ConnectFossResponse")]
        System.Threading.Tasks.Task<string> ConnectFossAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Equipment_QC", ReplyAction="http://tempuri.org/IService1/Equipment_QCResponse")]
        string Equipment_QC();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Equipment_QC", ReplyAction="http://tempuri.org/IService1/Equipment_QCResponse")]
        System.Threading.Tasks.Task<string> Equipment_QCAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectAlpha2", ReplyAction="http://tempuri.org/IService1/ConnectAlpha2Response")]
        string ConnectAlpha2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectAlpha2", ReplyAction="http://tempuri.org/IService1/ConnectAlpha2Response")]
        System.Threading.Tasks.Task<string> ConnectAlpha2Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectAscomlogistics", ReplyAction="http://tempuri.org/IService1/ConnectAscomlogisticsResponse")]
        string ConnectAscomlogistics();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectAscomlogistics", ReplyAction="http://tempuri.org/IService1/ConnectAscomlogisticsResponse")]
        System.Threading.Tasks.Task<string> ConnectAscomlogisticsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectBTG", ReplyAction="http://tempuri.org/IService1/ConnectBTGResponse")]
        string ConnectBTG();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectBTG", ReplyAction="http://tempuri.org/IService1/ConnectBTGResponse")]
        System.Threading.Tasks.Task<string> ConnectBTGAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectFlonidan", ReplyAction="http://tempuri.org/IService1/ConnectFlonidanResponse")]
        string ConnectFlonidan();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectFlonidan", ReplyAction="http://tempuri.org/IService1/ConnectFlonidanResponse")]
        System.Threading.Tasks.Task<string> ConnectFlonidanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectScanomat", ReplyAction="http://tempuri.org/IService1/ConnectScanomatResponse")]
        string ConnectScanomat();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectScanomat", ReplyAction="http://tempuri.org/IService1/ConnectScanomatResponse")]
        System.Threading.Tasks.Task<string> ConnectScanomatAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectHks", ReplyAction="http://tempuri.org/IService1/ConnectHksResponse")]
        string ConnectHks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectHks", ReplyAction="http://tempuri.org/IService1/ConnectHksResponse")]
        System.Threading.Tasks.Task<string> ConnectHksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Connectsam", ReplyAction="http://tempuri.org/IService1/ConnectsamResponse")]
        string Connectsam();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Connectsam", ReplyAction="http://tempuri.org/IService1/ConnectsamResponse")]
        System.Threading.Tasks.Task<string> ConnectsamAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Connectrdreport", ReplyAction="http://tempuri.org/IService1/ConnectrdreportResponse")]
        string Connectrdreport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Connectrdreport", ReplyAction="http://tempuri.org/IService1/ConnectrdreportResponse")]
        System.Threading.Tasks.Task<string> ConnectrdreportAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectBK", ReplyAction="http://tempuri.org/IService1/ConnectBKResponse")]
        string ConnectBK();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectBK", ReplyAction="http://tempuri.org/IService1/ConnectBKResponse")]
        System.Threading.Tasks.Task<string> ConnectBKAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectEppen", ReplyAction="http://tempuri.org/IService1/ConnectEppenResponse")]
        string ConnectEppen();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectEppen", ReplyAction="http://tempuri.org/IService1/ConnectEppenResponse")]
        System.Threading.Tasks.Task<string> ConnectEppenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectDanelec", ReplyAction="http://tempuri.org/IService1/ConnectDanelecResponse")]
        string ConnectDanelec();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectDanelec", ReplyAction="http://tempuri.org/IService1/ConnectDanelecResponse")]
        System.Threading.Tasks.Task<string> ConnectDanelecAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Connectpacking", ReplyAction="http://tempuri.org/IService1/ConnectpackingResponse")]
        string Connectpacking();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Connectpacking", ReplyAction="http://tempuri.org/IService1/ConnectpackingResponse")]
        System.Threading.Tasks.Task<string> ConnectpackingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Connectpackingweb", ReplyAction="http://tempuri.org/IService1/ConnectpackingwebResponse")]
        string Connectpackingweb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Connectpackingweb", ReplyAction="http://tempuri.org/IService1/ConnectpackingwebResponse")]
        System.Threading.Tasks.Task<string> ConnectpackingwebAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        MAFixture_WebApplication.WCF227Service.CompositeType GetDataUsingDataContract(MAFixture_WebApplication.WCF227Service.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<MAFixture_WebApplication.WCF227Service.CompositeType> GetDataUsingDataContractAsync(MAFixture_WebApplication.WCF227Service.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetdateYYYY_MM_dd", ReplyAction="http://tempuri.org/IService1/GetdateYYYY_MM_ddResponse")]
        string GetdateYYYY_MM_dd();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetdateYYYY_MM_dd", ReplyAction="http://tempuri.org/IService1/GetdateYYYY_MM_ddResponse")]
        System.Threading.Tasks.Task<string> GetdateYYYY_MM_ddAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectAscomlogisticsVB6", ReplyAction="http://tempuri.org/IService1/ConnectAscomlogisticsVB6Response")]
        string ConnectAscomlogisticsVB6();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectAscomlogisticsVB6", ReplyAction="http://tempuri.org/IService1/ConnectAscomlogisticsVB6Response")]
        System.Threading.Tasks.Task<string> ConnectAscomlogisticsVB6Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Grundfos_pr84", ReplyAction="http://tempuri.org/IService1/Grundfos_pr84Response")]
        string Grundfos_pr84();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Grundfos_pr84", ReplyAction="http://tempuri.org/IService1/Grundfos_pr84Response")]
        System.Threading.Tasks.Task<string> Grundfos_pr84Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectUltraelec", ReplyAction="http://tempuri.org/IService1/ConnectUltraelecResponse")]
        string ConnectUltraelec();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectUltraelec", ReplyAction="http://tempuri.org/IService1/ConnectUltraelecResponse")]
        System.Threading.Tasks.Task<string> ConnectUltraelecAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectMPC", ReplyAction="http://tempuri.org/IService1/ConnectMPCResponse")]
        string ConnectMPC();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectMPC", ReplyAction="http://tempuri.org/IService1/ConnectMPCResponse")]
        System.Threading.Tasks.Task<string> ConnectMPCAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHostemail", ReplyAction="http://tempuri.org/IService1/GetHostemailResponse")]
        string GetHostemail();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHostemail", ReplyAction="http://tempuri.org/IService1/GetHostemailResponse")]
        System.Threading.Tasks.Task<string> GetHostemailAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectNPIdatabase", ReplyAction="http://tempuri.org/IService1/ConnectNPIdatabaseResponse")]
        string ConnectNPIdatabase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectNPIdatabase", ReplyAction="http://tempuri.org/IService1/ConnectNPIdatabaseResponse")]
        System.Threading.Tasks.Task<string> ConnectNPIdatabaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectTrainingdatabase", ReplyAction="http://tempuri.org/IService1/ConnectTrainingdatabaseResponse")]
        string ConnectTrainingdatabase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectTrainingdatabase", ReplyAction="http://tempuri.org/IService1/ConnectTrainingdatabaseResponse")]
        System.Threading.Tasks.Task<string> ConnectTrainingdatabaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectMobility", ReplyAction="http://tempuri.org/IService1/ConnectMobilityResponse")]
        string ConnectMobility();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectMobility", ReplyAction="http://tempuri.org/IService1/ConnectMobilityResponse")]
        System.Threading.Tasks.Task<string> ConnectMobilityAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmailGroupPC", ReplyAction="http://tempuri.org/IService1/GetEmailGroupPCResponse")]
        string GetEmailGroupPC();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmailGroupPC", ReplyAction="http://tempuri.org/IService1/GetEmailGroupPCResponse")]
        System.Threading.Tasks.Task<string> GetEmailGroupPCAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSMTstencil", ReplyAction="http://tempuri.org/IService1/ConnectSMTstencilResponse")]
        string ConnectSMTstencil();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSMTstencil", ReplyAction="http://tempuri.org/IService1/ConnectSMTstencilResponse")]
        System.Threading.Tasks.Task<string> ConnectSMTstencilAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectRDjobrequestonline", ReplyAction="http://tempuri.org/IService1/ConnectRDjobrequestonlineResponse")]
        string ConnectRDjobrequestonline();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectRDjobrequestonline", ReplyAction="http://tempuri.org/IService1/ConnectRDjobrequestonlineResponse")]
        System.Threading.Tasks.Task<string> ConnectRDjobrequestonlineAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectGPVamericas", ReplyAction="http://tempuri.org/IService1/ConnectGPVamericasResponse")]
        string ConnectGPVamericas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectGPVamericas", ReplyAction="http://tempuri.org/IService1/ConnectGPVamericasResponse")]
        System.Threading.Tasks.Task<string> ConnectGPVamericasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectPTDsystem", ReplyAction="http://tempuri.org/IService1/ConnectPTDsystemResponse")]
        string ConnectPTDsystem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectPTDsystem", ReplyAction="http://tempuri.org/IService1/ConnectPTDsystemResponse")]
        System.Threading.Tasks.Task<string> ConnectPTDsystemAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectTPproject", ReplyAction="http://tempuri.org/IService1/ConnectTPprojectResponse")]
        string ConnectTPproject();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectTPproject", ReplyAction="http://tempuri.org/IService1/ConnectTPprojectResponse")]
        System.Threading.Tasks.Task<string> ConnectTPprojectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectKaizen", ReplyAction="http://tempuri.org/IService1/ConnectKaizenResponse")]
        string ConnectKaizen();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectKaizen", ReplyAction="http://tempuri.org/IService1/ConnectKaizenResponse")]
        System.Threading.Tasks.Task<string> ConnectKaizenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectG4S", ReplyAction="http://tempuri.org/IService1/ConnectG4SResponse")]
        string ConnectG4S();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectG4S", ReplyAction="http://tempuri.org/IService1/ConnectG4SResponse")]
        System.Threading.Tasks.Task<string> ConnectG4SAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectMXascom", ReplyAction="http://tempuri.org/IService1/ConnectMXascomResponse")]
        string ConnectMXascom();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectMXascom", ReplyAction="http://tempuri.org/IService1/ConnectMXascomResponse")]
        System.Threading.Tasks.Task<string> ConnectMXascomAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectPrototype", ReplyAction="http://tempuri.org/IService1/ConnectPrototypeResponse")]
        string ConnectPrototype();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectPrototype", ReplyAction="http://tempuri.org/IService1/ConnectPrototypeResponse")]
        System.Threading.Tasks.Task<string> ConnectPrototypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectMitaTeknik", ReplyAction="http://tempuri.org/IService1/ConnectMitaTeknikResponse")]
        string ConnectMitaTeknik();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectMitaTeknik", ReplyAction="http://tempuri.org/IService1/ConnectMitaTeknikResponse")]
        System.Threading.Tasks.Task<string> ConnectMitaTeknikAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectMitaCustomer", ReplyAction="http://tempuri.org/IService1/ConnectMitaCustomerResponse")]
        string ConnectMitaCustomer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectMitaCustomer", ReplyAction="http://tempuri.org/IService1/ConnectMitaCustomerResponse")]
        System.Threading.Tasks.Task<string> ConnectMitaCustomerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectMitaCustomer_Test", ReplyAction="http://tempuri.org/IService1/ConnectMitaCustomer_TestResponse")]
        string ConnectMitaCustomer_Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectMitaCustomer_Test", ReplyAction="http://tempuri.org/IService1/ConnectMitaCustomer_TestResponse")]
        System.Threading.Tasks.Task<string> ConnectMitaCustomer_TestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FinddayofYear", ReplyAction="http://tempuri.org/IService1/FinddayofYearResponse")]
        string FinddayofYear(string d, string m, string y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FinddayofYear", ReplyAction="http://tempuri.org/IService1/FinddayofYearResponse")]
        System.Threading.Tasks.Task<string> FinddayofYearAsync(string d, string m, string y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectEngineeringReport", ReplyAction="http://tempuri.org/IService1/ConnectEngineeringReportResponse")]
        string ConnectEngineeringReport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectEngineeringReport", ReplyAction="http://tempuri.org/IService1/ConnectEngineeringReportResponse")]
        System.Threading.Tasks.Task<string> ConnectEngineeringReportAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectQCcalibration", ReplyAction="http://tempuri.org/IService1/ConnectQCcalibrationResponse")]
        string ConnectQCcalibration();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectQCcalibration", ReplyAction="http://tempuri.org/IService1/ConnectQCcalibrationResponse")]
        System.Threading.Tasks.Task<string> ConnectQCcalibrationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectCostapproval", ReplyAction="http://tempuri.org/IService1/ConnectCostapprovalResponse")]
        string ConnectCostapproval();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectCostapproval", ReplyAction="http://tempuri.org/IService1/ConnectCostapprovalResponse")]
        System.Threading.Tasks.Task<string> ConnectCostapprovalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectTroubleShooting", ReplyAction="http://tempuri.org/IService1/ConnectTroubleShootingResponse")]
        string ConnectTroubleShooting();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectTroubleShooting", ReplyAction="http://tempuri.org/IService1/ConnectTroubleShootingResponse")]
        System.Threading.Tasks.Task<string> ConnectTroubleShootingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectLingaard", ReplyAction="http://tempuri.org/IService1/ConnectLingaardResponse")]
        string ConnectLingaard();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectLingaard", ReplyAction="http://tempuri.org/IService1/ConnectLingaardResponse")]
        System.Threading.Tasks.Task<string> ConnectLingaardAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectCostapprovalMX", ReplyAction="http://tempuri.org/IService1/ConnectCostapprovalMXResponse")]
        string ConnectCostapprovalMX();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectCostapprovalMX", ReplyAction="http://tempuri.org/IService1/ConnectCostapprovalMXResponse")]
        System.Threading.Tasks.Task<string> ConnectCostapprovalMXAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectStoreEquipment", ReplyAction="http://tempuri.org/IService1/ConnectStoreEquipmentResponse")]
        string ConnectStoreEquipment();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectStoreEquipment", ReplyAction="http://tempuri.org/IService1/ConnectStoreEquipmentResponse")]
        System.Threading.Tasks.Task<string> ConnectStoreEquipmentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectMecQCcalibration", ReplyAction="http://tempuri.org/IService1/ConnectMecQCcalibrationResponse")]
        string ConnectMecQCcalibration();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectMecQCcalibration", ReplyAction="http://tempuri.org/IService1/ConnectMecQCcalibrationResponse")]
        System.Threading.Tasks.Task<string> ConnectMecQCcalibrationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectImageAOI", ReplyAction="http://tempuri.org/IService1/ConnectImageAOIResponse")]
        string ConnectImageAOI(string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectImageAOI", ReplyAction="http://tempuri.org/IService1/ConnectImageAOIResponse")]
        System.Threading.Tasks.Task<string> ConnectImageAOIAsync(string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSMTAOIREPORT", ReplyAction="http://tempuri.org/IService1/ConnectSMTAOIREPORTResponse")]
        string ConnectSMTAOIREPORT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSMTAOIREPORT", ReplyAction="http://tempuri.org/IService1/ConnectSMTAOIREPORTResponse")]
        System.Threading.Tasks.Task<string> ConnectSMTAOIREPORTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectKArequest", ReplyAction="http://tempuri.org/IService1/ConnectKArequestResponse")]
        string ConnectKArequest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectKArequest", ReplyAction="http://tempuri.org/IService1/ConnectKArequestResponse")]
        System.Threading.Tasks.Task<string> ConnectKArequestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectTestLogfiles", ReplyAction="http://tempuri.org/IService1/ConnectTestLogfilesResponse")]
        string ConnectTestLogfiles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectTestLogfiles", ReplyAction="http://tempuri.org/IService1/ConnectTestLogfilesResponse")]
        System.Threading.Tasks.Task<string> ConnectTestLogfilesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectWIPstatus", ReplyAction="http://tempuri.org/IService1/ConnectWIPstatusResponse")]
        string ConnectWIPstatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectWIPstatus", ReplyAction="http://tempuri.org/IService1/ConnectWIPstatusResponse")]
        System.Threading.Tasks.Task<string> ConnectWIPstatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectProductionWIP", ReplyAction="http://tempuri.org/IService1/ConnectProductionWIPResponse")]
        string ConnectProductionWIP();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectProductionWIP", ReplyAction="http://tempuri.org/IService1/ConnectProductionWIPResponse")]
        System.Threading.Tasks.Task<string> ConnectProductionWIPAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectTTadvanceMTH", ReplyAction="http://tempuri.org/IService1/ConnectTTadvanceMTHResponse")]
        string ConnectTTadvanceMTH();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectTTadvanceMTH", ReplyAction="http://tempuri.org/IService1/ConnectTTadvanceMTHResponse")]
        System.Threading.Tasks.Task<string> ConnectTTadvanceMTHAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectEmaildatabase", ReplyAction="http://tempuri.org/IService1/ConnectEmaildatabaseResponse")]
        string ConnectEmaildatabase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectEmaildatabase", ReplyAction="http://tempuri.org/IService1/ConnectEmaildatabaseResponse")]
        System.Threading.Tasks.Task<string> ConnectEmaildatabaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Getemailall", ReplyAction="http://tempuri.org/IService1/GetemailallResponse")]
        string[] Getemailall(string subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Getemailall", ReplyAction="http://tempuri.org/IService1/GetemailallResponse")]
        System.Threading.Tasks.Task<string[]> GetemailallAsync(string subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectCostsapprovalDK", ReplyAction="http://tempuri.org/IService1/ConnectCostsapprovalDKResponse")]
        string ConnectCostsapprovalDK();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectCostsapprovalDK", ReplyAction="http://tempuri.org/IService1/ConnectCostsapprovalDKResponse")]
        System.Threading.Tasks.Task<string> ConnectCostsapprovalDKAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectTrackerdatabase", ReplyAction="http://tempuri.org/IService1/ConnectTrackerdatabaseResponse")]
        string ConnectTrackerdatabase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectTrackerdatabase", ReplyAction="http://tempuri.org/IService1/ConnectTrackerdatabaseResponse")]
        System.Threading.Tasks.Task<string> ConnectTrackerdatabaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectGrundfos_Nonoise", ReplyAction="http://tempuri.org/IService1/ConnectGrundfos_NonoiseResponse")]
        string ConnectGrundfos_Nonoise();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectGrundfos_Nonoise", ReplyAction="http://tempuri.org/IService1/ConnectGrundfos_NonoiseResponse")]
        System.Threading.Tasks.Task<string> ConnectGrundfos_NonoiseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectIcepower", ReplyAction="http://tempuri.org/IService1/ConnectIcepowerResponse")]
        string ConnectIcepower();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectIcepower", ReplyAction="http://tempuri.org/IService1/ConnectIcepowerResponse")]
        System.Threading.Tasks.Task<string> ConnectIcepowerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectGrundfos_DHW", ReplyAction="http://tempuri.org/IService1/ConnectGrundfos_DHWResponse")]
        string ConnectGrundfos_DHW();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectGrundfos_DHW", ReplyAction="http://tempuri.org/IService1/ConnectGrundfos_DHWResponse")]
        System.Threading.Tasks.Task<string> ConnectGrundfos_DHWAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectBeckett", ReplyAction="http://tempuri.org/IService1/ConnectBeckettResponse")]
        string ConnectBeckett();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectBeckett", ReplyAction="http://tempuri.org/IService1/ConnectBeckettResponse")]
        System.Threading.Tasks.Task<string> ConnectBeckettAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectNorthInvent", ReplyAction="http://tempuri.org/IService1/ConnectNorthInventResponse")]
        string ConnectNorthInvent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectNorthInvent", ReplyAction="http://tempuri.org/IService1/ConnectNorthInventResponse")]
        System.Threading.Tasks.Task<string> ConnectNorthInventAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectWIonline", ReplyAction="http://tempuri.org/IService1/ConnectWIonlineResponse")]
        string ConnectWIonline();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectWIonline", ReplyAction="http://tempuri.org/IService1/ConnectWIonlineResponse")]
        System.Threading.Tasks.Task<string> ConnectWIonlineAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectAscomSPC", ReplyAction="http://tempuri.org/IService1/ConnectAscomSPCResponse")]
        string ConnectAscomSPC();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectAscomSPC", ReplyAction="http://tempuri.org/IService1/ConnectAscomSPCResponse")]
        System.Threading.Tasks.Task<string> ConnectAscomSPCAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectCostapprovalMTH", ReplyAction="http://tempuri.org/IService1/ConnectCostapprovalMTHResponse")]
        string ConnectCostapprovalMTH();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectCostapprovalMTH", ReplyAction="http://tempuri.org/IService1/ConnectCostapprovalMTHResponse")]
        System.Threading.Tasks.Task<string> ConnectCostapprovalMTHAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectITax", ReplyAction="http://tempuri.org/IService1/ConnectITaxResponse")]
        string ConnectITax();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectITax", ReplyAction="http://tempuri.org/IService1/ConnectITaxResponse")]
        System.Threading.Tasks.Task<string> ConnectITaxAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetdatTimeYYYY_MM_DD", ReplyAction="http://tempuri.org/IService1/GetdatTimeYYYY_MM_DDResponse")]
        string GetdatTimeYYYY_MM_DD();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetdatTimeYYYY_MM_DD", ReplyAction="http://tempuri.org/IService1/GetdatTimeYYYY_MM_DDResponse")]
        System.Threading.Tasks.Task<string> GetdatTimeYYYY_MM_DDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSFRdatabase", ReplyAction="http://tempuri.org/IService1/ConnectSFRdatabaseResponse")]
        string ConnectSFRdatabase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSFRdatabase", ReplyAction="http://tempuri.org/IService1/ConnectSFRdatabaseResponse")]
        System.Threading.Tasks.Task<string> ConnectSFRdatabaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectRFQdatabase", ReplyAction="http://tempuri.org/IService1/ConnectRFQdatabaseResponse")]
        string ConnectRFQdatabase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectRFQdatabase", ReplyAction="http://tempuri.org/IService1/ConnectRFQdatabaseResponse")]
        System.Threading.Tasks.Task<string> ConnectRFQdatabaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectPTDMTH", ReplyAction="http://tempuri.org/IService1/ConnectPTDMTHResponse")]
        string ConnectPTDMTH();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectPTDMTH", ReplyAction="http://tempuri.org/IService1/ConnectPTDMTHResponse")]
        System.Threading.Tasks.Task<string> ConnectPTDMTHAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSamvac", ReplyAction="http://tempuri.org/IService1/ConnectSamvacResponse")]
        string ConnectSamvac();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSamvac", ReplyAction="http://tempuri.org/IService1/ConnectSamvacResponse")]
        System.Threading.Tasks.Task<string> ConnectSamvacAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectLabelsystem", ReplyAction="http://tempuri.org/IService1/ConnectLabelsystemResponse")]
        string ConnectLabelsystem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectLabelsystem", ReplyAction="http://tempuri.org/IService1/ConnectLabelsystemResponse")]
        System.Threading.Tasks.Task<string> ConnectLabelsystemAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectPRdatabase", ReplyAction="http://tempuri.org/IService1/ConnectPRdatabaseResponse")]
        string ConnectPRdatabase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectPRdatabase", ReplyAction="http://tempuri.org/IService1/ConnectPRdatabaseResponse")]
        System.Threading.Tasks.Task<string> ConnectPRdatabaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectLattec", ReplyAction="http://tempuri.org/IService1/ConnectLattecResponse")]
        string ConnectLattec();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectLattec", ReplyAction="http://tempuri.org/IService1/ConnectLattecResponse")]
        System.Threading.Tasks.Task<string> ConnectLattecAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectRFQMTHdatabase", ReplyAction="http://tempuri.org/IService1/ConnectRFQMTHdatabaseResponse")]
        string ConnectRFQMTHdatabase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectRFQMTHdatabase", ReplyAction="http://tempuri.org/IService1/ConnectRFQMTHdatabaseResponse")]
        System.Threading.Tasks.Task<string> ConnectRFQMTHdatabaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectGambro", ReplyAction="http://tempuri.org/IService1/ConnectGambroResponse")]
        string ConnectGambro();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectGambro", ReplyAction="http://tempuri.org/IService1/ConnectGambroResponse")]
        System.Threading.Tasks.Task<string> ConnectGambroAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectHormann", ReplyAction="http://tempuri.org/IService1/ConnectHormannResponse")]
        string ConnectHormann();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectHormann", ReplyAction="http://tempuri.org/IService1/ConnectHormannResponse")]
        System.Threading.Tasks.Task<string> ConnectHormannAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetworkweekISO8601YYWww", ReplyAction="http://tempuri.org/IService1/GetworkweekISO8601YYWwwResponse")]
        string GetworkweekISO8601YYWww();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetworkweekISO8601YYWww", ReplyAction="http://tempuri.org/IService1/GetworkweekISO8601YYWwwResponse")]
        System.Threading.Tasks.Task<string> GetworkweekISO8601YYWwwAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GETworkweekISO8601WWYY", ReplyAction="http://tempuri.org/IService1/GETworkweekISO8601WWYYResponse")]
        string GETworkweekISO8601WWYY();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GETworkweekISO8601WWYY", ReplyAction="http://tempuri.org/IService1/GETworkweekISO8601WWYYResponse")]
        System.Threading.Tasks.Task<string> GETworkweekISO8601WWYYAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectElero", ReplyAction="http://tempuri.org/IService1/ConnectEleroResponse")]
        string ConnectElero();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectElero", ReplyAction="http://tempuri.org/IService1/ConnectEleroResponse")]
        System.Threading.Tasks.Task<string> ConnectEleroAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectBesi", ReplyAction="http://tempuri.org/IService1/ConnectBesiResponse")]
        string ConnectBesi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectBesi", ReplyAction="http://tempuri.org/IService1/ConnectBesiResponse")]
        System.Threading.Tasks.Task<string> ConnectBesiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectFlyingprobe", ReplyAction="http://tempuri.org/IService1/ConnectFlyingprobeResponse")]
        string ConnectFlyingprobe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectFlyingprobe", ReplyAction="http://tempuri.org/IService1/ConnectFlyingprobeResponse")]
        System.Threading.Tasks.Task<string> ConnectFlyingprobeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectEndress", ReplyAction="http://tempuri.org/IService1/ConnectEndressResponse")]
        string ConnectEndress();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectEndress", ReplyAction="http://tempuri.org/IService1/ConnectEndressResponse")]
        System.Threading.Tasks.Task<string> ConnectEndressAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSMTSchedule", ReplyAction="http://tempuri.org/IService1/ConnectSMTScheduleResponse")]
        string ConnectSMTSchedule();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSMTSchedule", ReplyAction="http://tempuri.org/IService1/ConnectSMTScheduleResponse")]
        System.Threading.Tasks.Task<string> ConnectSMTScheduleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectKPI", ReplyAction="http://tempuri.org/IService1/ConnectKPIResponse")]
        string ConnectKPI();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectKPI", ReplyAction="http://tempuri.org/IService1/ConnectKPIResponse")]
        System.Threading.Tasks.Task<string> ConnectKPIAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectQCrdserver", ReplyAction="http://tempuri.org/IService1/ConnectQCrdserverResponse")]
        string ConnectQCrdserver();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectQCrdserver", ReplyAction="http://tempuri.org/IService1/ConnectQCrdserverResponse")]
        System.Threading.Tasks.Task<string> ConnectQCrdserverAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectTestStand_Diversity", ReplyAction="http://tempuri.org/IService1/ConnectTestStand_DiversityResponse")]
        string ConnectTestStand_Diversity();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectTestStand_Diversity", ReplyAction="http://tempuri.org/IService1/ConnectTestStand_DiversityResponse")]
        System.Threading.Tasks.Task<string> ConnectTestStand_DiversityAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetemailbyAccountname", ReplyAction="http://tempuri.org/IService1/GetemailbyAccountnameResponse")]
        string GetemailbyAccountname(string accountname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetemailbyAccountname", ReplyAction="http://tempuri.org/IService1/GetemailbyAccountnameResponse")]
        System.Threading.Tasks.Task<string> GetemailbyAccountnameAsync(string accountname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetemailbyEmployeeID", ReplyAction="http://tempuri.org/IService1/GetemailbyEmployeeIDResponse")]
        string GetemailbyEmployeeID(string employeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetemailbyEmployeeID", ReplyAction="http://tempuri.org/IService1/GetemailbyEmployeeIDResponse")]
        System.Threading.Tasks.Task<string> GetemailbyEmployeeIDAsync(string employeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GETworkweekISO8601YYWW", ReplyAction="http://tempuri.org/IService1/GETworkweekISO8601YYWWResponse")]
        string GETworkweekISO8601YYWW();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GETworkweekISO8601YYWW", ReplyAction="http://tempuri.org/IService1/GETworkweekISO8601YYWWResponse")]
        System.Threading.Tasks.Task<string> GETworkweekISO8601YYWWAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectFlowserve", ReplyAction="http://tempuri.org/IService1/ConnectFlowserveResponse")]
        string ConnectFlowserve();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectFlowserve", ReplyAction="http://tempuri.org/IService1/ConnectFlowserveResponse")]
        System.Threading.Tasks.Task<string> ConnectFlowserveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Connectftpascom", ReplyAction="http://tempuri.org/IService1/ConnectftpascomResponse")]
        string Connectftpascom();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Connectftpascom", ReplyAction="http://tempuri.org/IService1/ConnectftpascomResponse")]
        System.Threading.Tasks.Task<string> ConnectftpascomAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GETworkweekISO8601WWSYYYY", ReplyAction="http://tempuri.org/IService1/GETworkweekISO8601WWSYYYYResponse")]
        string GETworkweekISO8601WWSYYYY();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GETworkweekISO8601WWSYYYY", ReplyAction="http://tempuri.org/IService1/GETworkweekISO8601WWSYYYYResponse")]
        System.Threading.Tasks.Task<string> GETworkweekISO8601WWSYYYYAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWIPbyworkorder", ReplyAction="http://tempuri.org/IService1/GetWIPbyworkorderResponse")]
        System.Data.DataSet GetWIPbyworkorder(string Workorder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWIPbyworkorder", ReplyAction="http://tempuri.org/IService1/GetWIPbyworkorderResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetWIPbyworkorderAsync(string Workorder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectTeledyne", ReplyAction="http://tempuri.org/IService1/ConnectTeledyneResponse")]
        string ConnectTeledyne();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectTeledyne", ReplyAction="http://tempuri.org/IService1/ConnectTeledyneResponse")]
        System.Threading.Tasks.Task<string> ConnectTeledyneAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectDieboldNixdorf", ReplyAction="http://tempuri.org/IService1/ConnectDieboldNixdorfResponse")]
        string ConnectDieboldNixdorf();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectDieboldNixdorf", ReplyAction="http://tempuri.org/IService1/ConnectDieboldNixdorfResponse")]
        System.Threading.Tasks.Task<string> ConnectDieboldNixdorfAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSeisenbacher", ReplyAction="http://tempuri.org/IService1/ConnectSeisenbacherResponse")]
        string ConnectSeisenbacher();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectSeisenbacher", ReplyAction="http://tempuri.org/IService1/ConnectSeisenbacherResponse")]
        System.Threading.Tasks.Task<string> ConnectSeisenbacherAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Convertemailfromlisttostring", ReplyAction="http://tempuri.org/IService1/ConvertemailfromlisttostringResponse")]
        string Convertemailfromlisttostring(string[] Emailteam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Convertemailfromlisttostring", ReplyAction="http://tempuri.org/IService1/ConvertemailfromlisttostringResponse")]
        System.Threading.Tasks.Task<string> ConvertemailfromlisttostringAsync(string[] Emailteam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Convertemailfromstring", ReplyAction="http://tempuri.org/IService1/ConvertemailfromstringResponse")]
        string Convertemailfromstring(string Emailteam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Convertemailfromstring", ReplyAction="http://tempuri.org/IService1/ConvertemailfromstringResponse")]
        System.Threading.Tasks.Task<string> ConvertemailfromstringAsync(string Emailteam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectGavilar", ReplyAction="http://tempuri.org/IService1/ConnectGavilarResponse")]
        string ConnectGavilar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectGavilar", ReplyAction="http://tempuri.org/IService1/ConnectGavilarResponse")]
        System.Threading.Tasks.Task<string> ConnectGavilarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectWindowmasterCustomer", ReplyAction="http://tempuri.org/IService1/ConnectWindowmasterCustomerResponse")]
        string ConnectWindowmasterCustomer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectWindowmasterCustomer", ReplyAction="http://tempuri.org/IService1/ConnectWindowmasterCustomerResponse")]
        System.Threading.Tasks.Task<string> ConnectWindowmasterCustomerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStart_EnddateofLastmonth", ReplyAction="http://tempuri.org/IService1/GetStart_EnddateofLastmonthResponse")]
        string[] GetStart_EnddateofLastmonth();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStart_EnddateofLastmonth", ReplyAction="http://tempuri.org/IService1/GetStart_EnddateofLastmonthResponse")]
        System.Threading.Tasks.Task<string[]> GetStart_EnddateofLastmonthAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectDanfoss", ReplyAction="http://tempuri.org/IService1/ConnectDanfossResponse")]
        string ConnectDanfoss();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectDanfoss", ReplyAction="http://tempuri.org/IService1/ConnectDanfossResponse")]
        System.Threading.Tasks.Task<string> ConnectDanfossAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAccountNamebyEmail", ReplyAction="http://tempuri.org/IService1/GetAccountNamebyEmailResponse")]
        string GetAccountNamebyEmail(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAccountNamebyEmail", ReplyAction="http://tempuri.org/IService1/GetAccountNamebyEmailResponse")]
        System.Threading.Tasks.Task<string> GetAccountNamebyEmailAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Getdatedd_MM_yy", ReplyAction="http://tempuri.org/IService1/Getdatedd_MM_yyResponse")]
        string Getdatedd_MM_yy();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Getdatedd_MM_yy", ReplyAction="http://tempuri.org/IService1/Getdatedd_MM_yyResponse")]
        System.Threading.Tasks.Task<string> Getdatedd_MM_yyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Getdateyyy_MM_dd", ReplyAction="http://tempuri.org/IService1/Getdateyyy_MM_ddResponse")]
        string Getdateyyy_MM_dd();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Getdateyyy_MM_dd", ReplyAction="http://tempuri.org/IService1/Getdateyyy_MM_ddResponse")]
        System.Threading.Tasks.Task<string> Getdateyyy_MM_ddAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Getdatedd_MM_yy_HHmmss", ReplyAction="http://tempuri.org/IService1/Getdatedd_MM_yy_HHmmssResponse")]
        string Getdatedd_MM_yy_HHmmss();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Getdatedd_MM_yy_HHmmss", ReplyAction="http://tempuri.org/IService1/Getdatedd_MM_yy_HHmmssResponse")]
        System.Threading.Tasks.Task<string> Getdatedd_MM_yy_HHmmssAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConvertEmailDuplicate", ReplyAction="http://tempuri.org/IService1/ConvertEmailDuplicateResponse")]
        string ConvertEmailDuplicate(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConvertEmailDuplicate", ReplyAction="http://tempuri.org/IService1/ConvertEmailDuplicateResponse")]
        System.Threading.Tasks.Task<string> ConvertEmailDuplicateAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWeekOfMonth", ReplyAction="http://tempuri.org/IService1/GetWeekOfMonthResponse")]
        int GetWeekOfMonth(System.DateTime dateValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWeekOfMonth", ReplyAction="http://tempuri.org/IService1/GetWeekOfMonthResponse")]
        System.Threading.Tasks.Task<int> GetWeekOfMonthAsync(System.DateTime dateValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Removeemailfromgroup", ReplyAction="http://tempuri.org/IService1/RemoveemailfromgroupResponse")]
        string Removeemailfromgroup(string Emailall, string RemoveEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Removeemailfromgroup", ReplyAction="http://tempuri.org/IService1/RemoveemailfromgroupResponse")]
        System.Threading.Tasks.Task<string> RemoveemailfromgroupAsync(string Emailall, string RemoveEmail);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MAFixture_WebApplication.WCF227Service.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MAFixture_WebApplication.WCF227Service.IService1>, MAFixture_WebApplication.WCF227Service.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ConnectBOM_Checking() {
            return base.Channel.ConnectBOM_Checking();
        }
        
        public System.Threading.Tasks.Task<string> ConnectBOM_CheckingAsync() {
            return base.Channel.ConnectBOM_CheckingAsync();
        }
        
        public string ConnectSTM() {
            return base.Channel.ConnectSTM();
        }
        
        public System.Threading.Tasks.Task<string> ConnectSTMAsync() {
            return base.Channel.ConnectSTMAsync();
        }
        
        public string Microscan_new() {
            return base.Channel.Microscan_new();
        }
        
        public System.Threading.Tasks.Task<string> Microscan_newAsync() {
            return base.Channel.Microscan_newAsync();
        }
        
        public string Grundfos_pr() {
            return base.Channel.Grundfos_pr();
        }
        
        public System.Threading.Tasks.Task<string> Grundfos_prAsync() {
            return base.Channel.Grundfos_prAsync();
        }
        
        public string ConnectGNO() {
            return base.Channel.ConnectGNO();
        }
        
        public System.Threading.Tasks.Task<string> ConnectGNOAsync() {
            return base.Channel.ConnectGNOAsync();
        }
        
        public string ConnectFoss() {
            return base.Channel.ConnectFoss();
        }
        
        public System.Threading.Tasks.Task<string> ConnectFossAsync() {
            return base.Channel.ConnectFossAsync();
        }
        
        public string Equipment_QC() {
            return base.Channel.Equipment_QC();
        }
        
        public System.Threading.Tasks.Task<string> Equipment_QCAsync() {
            return base.Channel.Equipment_QCAsync();
        }
        
        public string ConnectAlpha2() {
            return base.Channel.ConnectAlpha2();
        }
        
        public System.Threading.Tasks.Task<string> ConnectAlpha2Async() {
            return base.Channel.ConnectAlpha2Async();
        }
        
        public string ConnectAscomlogistics() {
            return base.Channel.ConnectAscomlogistics();
        }
        
        public System.Threading.Tasks.Task<string> ConnectAscomlogisticsAsync() {
            return base.Channel.ConnectAscomlogisticsAsync();
        }
        
        public string ConnectBTG() {
            return base.Channel.ConnectBTG();
        }
        
        public System.Threading.Tasks.Task<string> ConnectBTGAsync() {
            return base.Channel.ConnectBTGAsync();
        }
        
        public string ConnectFlonidan() {
            return base.Channel.ConnectFlonidan();
        }
        
        public System.Threading.Tasks.Task<string> ConnectFlonidanAsync() {
            return base.Channel.ConnectFlonidanAsync();
        }
        
        public string ConnectScanomat() {
            return base.Channel.ConnectScanomat();
        }
        
        public System.Threading.Tasks.Task<string> ConnectScanomatAsync() {
            return base.Channel.ConnectScanomatAsync();
        }
        
        public string ConnectHks() {
            return base.Channel.ConnectHks();
        }
        
        public System.Threading.Tasks.Task<string> ConnectHksAsync() {
            return base.Channel.ConnectHksAsync();
        }
        
        public string Connectsam() {
            return base.Channel.Connectsam();
        }
        
        public System.Threading.Tasks.Task<string> ConnectsamAsync() {
            return base.Channel.ConnectsamAsync();
        }
        
        public string Connectrdreport() {
            return base.Channel.Connectrdreport();
        }
        
        public System.Threading.Tasks.Task<string> ConnectrdreportAsync() {
            return base.Channel.ConnectrdreportAsync();
        }
        
        public string ConnectBK() {
            return base.Channel.ConnectBK();
        }
        
        public System.Threading.Tasks.Task<string> ConnectBKAsync() {
            return base.Channel.ConnectBKAsync();
        }
        
        public string ConnectEppen() {
            return base.Channel.ConnectEppen();
        }
        
        public System.Threading.Tasks.Task<string> ConnectEppenAsync() {
            return base.Channel.ConnectEppenAsync();
        }
        
        public string ConnectDanelec() {
            return base.Channel.ConnectDanelec();
        }
        
        public System.Threading.Tasks.Task<string> ConnectDanelecAsync() {
            return base.Channel.ConnectDanelecAsync();
        }
        
        public string Connectpacking() {
            return base.Channel.Connectpacking();
        }
        
        public System.Threading.Tasks.Task<string> ConnectpackingAsync() {
            return base.Channel.ConnectpackingAsync();
        }
        
        public string Connectpackingweb() {
            return base.Channel.Connectpackingweb();
        }
        
        public System.Threading.Tasks.Task<string> ConnectpackingwebAsync() {
            return base.Channel.ConnectpackingwebAsync();
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public MAFixture_WebApplication.WCF227Service.CompositeType GetDataUsingDataContract(MAFixture_WebApplication.WCF227Service.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<MAFixture_WebApplication.WCF227Service.CompositeType> GetDataUsingDataContractAsync(MAFixture_WebApplication.WCF227Service.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string GetdateYYYY_MM_dd() {
            return base.Channel.GetdateYYYY_MM_dd();
        }
        
        public System.Threading.Tasks.Task<string> GetdateYYYY_MM_ddAsync() {
            return base.Channel.GetdateYYYY_MM_ddAsync();
        }
        
        public string ConnectAscomlogisticsVB6() {
            return base.Channel.ConnectAscomlogisticsVB6();
        }
        
        public System.Threading.Tasks.Task<string> ConnectAscomlogisticsVB6Async() {
            return base.Channel.ConnectAscomlogisticsVB6Async();
        }
        
        public string Grundfos_pr84() {
            return base.Channel.Grundfos_pr84();
        }
        
        public System.Threading.Tasks.Task<string> Grundfos_pr84Async() {
            return base.Channel.Grundfos_pr84Async();
        }
        
        public string ConnectUltraelec() {
            return base.Channel.ConnectUltraelec();
        }
        
        public System.Threading.Tasks.Task<string> ConnectUltraelecAsync() {
            return base.Channel.ConnectUltraelecAsync();
        }
        
        public string ConnectMPC() {
            return base.Channel.ConnectMPC();
        }
        
        public System.Threading.Tasks.Task<string> ConnectMPCAsync() {
            return base.Channel.ConnectMPCAsync();
        }
        
        public string GetHostemail() {
            return base.Channel.GetHostemail();
        }
        
        public System.Threading.Tasks.Task<string> GetHostemailAsync() {
            return base.Channel.GetHostemailAsync();
        }
        
        public string ConnectNPIdatabase() {
            return base.Channel.ConnectNPIdatabase();
        }
        
        public System.Threading.Tasks.Task<string> ConnectNPIdatabaseAsync() {
            return base.Channel.ConnectNPIdatabaseAsync();
        }
        
        public string ConnectTrainingdatabase() {
            return base.Channel.ConnectTrainingdatabase();
        }
        
        public System.Threading.Tasks.Task<string> ConnectTrainingdatabaseAsync() {
            return base.Channel.ConnectTrainingdatabaseAsync();
        }
        
        public string ConnectMobility() {
            return base.Channel.ConnectMobility();
        }
        
        public System.Threading.Tasks.Task<string> ConnectMobilityAsync() {
            return base.Channel.ConnectMobilityAsync();
        }
        
        public string GetEmailGroupPC() {
            return base.Channel.GetEmailGroupPC();
        }
        
        public System.Threading.Tasks.Task<string> GetEmailGroupPCAsync() {
            return base.Channel.GetEmailGroupPCAsync();
        }
        
        public string ConnectSMTstencil() {
            return base.Channel.ConnectSMTstencil();
        }
        
        public System.Threading.Tasks.Task<string> ConnectSMTstencilAsync() {
            return base.Channel.ConnectSMTstencilAsync();
        }
        
        public string ConnectRDjobrequestonline() {
            return base.Channel.ConnectRDjobrequestonline();
        }
        
        public System.Threading.Tasks.Task<string> ConnectRDjobrequestonlineAsync() {
            return base.Channel.ConnectRDjobrequestonlineAsync();
        }
        
        public string ConnectGPVamericas() {
            return base.Channel.ConnectGPVamericas();
        }
        
        public System.Threading.Tasks.Task<string> ConnectGPVamericasAsync() {
            return base.Channel.ConnectGPVamericasAsync();
        }
        
        public string ConnectPTDsystem() {
            return base.Channel.ConnectPTDsystem();
        }
        
        public System.Threading.Tasks.Task<string> ConnectPTDsystemAsync() {
            return base.Channel.ConnectPTDsystemAsync();
        }
        
        public string ConnectTPproject() {
            return base.Channel.ConnectTPproject();
        }
        
        public System.Threading.Tasks.Task<string> ConnectTPprojectAsync() {
            return base.Channel.ConnectTPprojectAsync();
        }
        
        public string ConnectKaizen() {
            return base.Channel.ConnectKaizen();
        }
        
        public System.Threading.Tasks.Task<string> ConnectKaizenAsync() {
            return base.Channel.ConnectKaizenAsync();
        }
        
        public string ConnectG4S() {
            return base.Channel.ConnectG4S();
        }
        
        public System.Threading.Tasks.Task<string> ConnectG4SAsync() {
            return base.Channel.ConnectG4SAsync();
        }
        
        public string ConnectMXascom() {
            return base.Channel.ConnectMXascom();
        }
        
        public System.Threading.Tasks.Task<string> ConnectMXascomAsync() {
            return base.Channel.ConnectMXascomAsync();
        }
        
        public string ConnectPrototype() {
            return base.Channel.ConnectPrototype();
        }
        
        public System.Threading.Tasks.Task<string> ConnectPrototypeAsync() {
            return base.Channel.ConnectPrototypeAsync();
        }
        
        public string ConnectMitaTeknik() {
            return base.Channel.ConnectMitaTeknik();
        }
        
        public System.Threading.Tasks.Task<string> ConnectMitaTeknikAsync() {
            return base.Channel.ConnectMitaTeknikAsync();
        }
        
        public string ConnectMitaCustomer() {
            return base.Channel.ConnectMitaCustomer();
        }
        
        public System.Threading.Tasks.Task<string> ConnectMitaCustomerAsync() {
            return base.Channel.ConnectMitaCustomerAsync();
        }
        
        public string ConnectMitaCustomer_Test() {
            return base.Channel.ConnectMitaCustomer_Test();
        }
        
        public System.Threading.Tasks.Task<string> ConnectMitaCustomer_TestAsync() {
            return base.Channel.ConnectMitaCustomer_TestAsync();
        }
        
        public string FinddayofYear(string d, string m, string y) {
            return base.Channel.FinddayofYear(d, m, y);
        }
        
        public System.Threading.Tasks.Task<string> FinddayofYearAsync(string d, string m, string y) {
            return base.Channel.FinddayofYearAsync(d, m, y);
        }
        
        public string ConnectEngineeringReport() {
            return base.Channel.ConnectEngineeringReport();
        }
        
        public System.Threading.Tasks.Task<string> ConnectEngineeringReportAsync() {
            return base.Channel.ConnectEngineeringReportAsync();
        }
        
        public string ConnectQCcalibration() {
            return base.Channel.ConnectQCcalibration();
        }
        
        public System.Threading.Tasks.Task<string> ConnectQCcalibrationAsync() {
            return base.Channel.ConnectQCcalibrationAsync();
        }
        
        public string ConnectCostapproval() {
            return base.Channel.ConnectCostapproval();
        }
        
        public System.Threading.Tasks.Task<string> ConnectCostapprovalAsync() {
            return base.Channel.ConnectCostapprovalAsync();
        }
        
        public string ConnectTroubleShooting() {
            return base.Channel.ConnectTroubleShooting();
        }
        
        public System.Threading.Tasks.Task<string> ConnectTroubleShootingAsync() {
            return base.Channel.ConnectTroubleShootingAsync();
        }
        
        public string ConnectLingaard() {
            return base.Channel.ConnectLingaard();
        }
        
        public System.Threading.Tasks.Task<string> ConnectLingaardAsync() {
            return base.Channel.ConnectLingaardAsync();
        }
        
        public string ConnectCostapprovalMX() {
            return base.Channel.ConnectCostapprovalMX();
        }
        
        public System.Threading.Tasks.Task<string> ConnectCostapprovalMXAsync() {
            return base.Channel.ConnectCostapprovalMXAsync();
        }
        
        public string ConnectStoreEquipment() {
            return base.Channel.ConnectStoreEquipment();
        }
        
        public System.Threading.Tasks.Task<string> ConnectStoreEquipmentAsync() {
            return base.Channel.ConnectStoreEquipmentAsync();
        }
        
        public string ConnectMecQCcalibration() {
            return base.Channel.ConnectMecQCcalibration();
        }
        
        public System.Threading.Tasks.Task<string> ConnectMecQCcalibrationAsync() {
            return base.Channel.ConnectMecQCcalibrationAsync();
        }
        
        public string ConnectImageAOI(string year) {
            return base.Channel.ConnectImageAOI(year);
        }
        
        public System.Threading.Tasks.Task<string> ConnectImageAOIAsync(string year) {
            return base.Channel.ConnectImageAOIAsync(year);
        }
        
        public string ConnectSMTAOIREPORT() {
            return base.Channel.ConnectSMTAOIREPORT();
        }
        
        public System.Threading.Tasks.Task<string> ConnectSMTAOIREPORTAsync() {
            return base.Channel.ConnectSMTAOIREPORTAsync();
        }
        
        public string ConnectKArequest() {
            return base.Channel.ConnectKArequest();
        }
        
        public System.Threading.Tasks.Task<string> ConnectKArequestAsync() {
            return base.Channel.ConnectKArequestAsync();
        }
        
        public string ConnectTestLogfiles() {
            return base.Channel.ConnectTestLogfiles();
        }
        
        public System.Threading.Tasks.Task<string> ConnectTestLogfilesAsync() {
            return base.Channel.ConnectTestLogfilesAsync();
        }
        
        public string ConnectWIPstatus() {
            return base.Channel.ConnectWIPstatus();
        }
        
        public System.Threading.Tasks.Task<string> ConnectWIPstatusAsync() {
            return base.Channel.ConnectWIPstatusAsync();
        }
        
        public string ConnectProductionWIP() {
            return base.Channel.ConnectProductionWIP();
        }
        
        public System.Threading.Tasks.Task<string> ConnectProductionWIPAsync() {
            return base.Channel.ConnectProductionWIPAsync();
        }
        
        public string ConnectTTadvanceMTH() {
            return base.Channel.ConnectTTadvanceMTH();
        }
        
        public System.Threading.Tasks.Task<string> ConnectTTadvanceMTHAsync() {
            return base.Channel.ConnectTTadvanceMTHAsync();
        }
        
        public string ConnectEmaildatabase() {
            return base.Channel.ConnectEmaildatabase();
        }
        
        public System.Threading.Tasks.Task<string> ConnectEmaildatabaseAsync() {
            return base.Channel.ConnectEmaildatabaseAsync();
        }
        
        public string[] Getemailall(string subject) {
            return base.Channel.Getemailall(subject);
        }
        
        public System.Threading.Tasks.Task<string[]> GetemailallAsync(string subject) {
            return base.Channel.GetemailallAsync(subject);
        }
        
        public string ConnectCostsapprovalDK() {
            return base.Channel.ConnectCostsapprovalDK();
        }
        
        public System.Threading.Tasks.Task<string> ConnectCostsapprovalDKAsync() {
            return base.Channel.ConnectCostsapprovalDKAsync();
        }
        
        public string ConnectTrackerdatabase() {
            return base.Channel.ConnectTrackerdatabase();
        }
        
        public System.Threading.Tasks.Task<string> ConnectTrackerdatabaseAsync() {
            return base.Channel.ConnectTrackerdatabaseAsync();
        }
        
        public string ConnectGrundfos_Nonoise() {
            return base.Channel.ConnectGrundfos_Nonoise();
        }
        
        public System.Threading.Tasks.Task<string> ConnectGrundfos_NonoiseAsync() {
            return base.Channel.ConnectGrundfos_NonoiseAsync();
        }
        
        public string ConnectIcepower() {
            return base.Channel.ConnectIcepower();
        }
        
        public System.Threading.Tasks.Task<string> ConnectIcepowerAsync() {
            return base.Channel.ConnectIcepowerAsync();
        }
        
        public string ConnectGrundfos_DHW() {
            return base.Channel.ConnectGrundfos_DHW();
        }
        
        public System.Threading.Tasks.Task<string> ConnectGrundfos_DHWAsync() {
            return base.Channel.ConnectGrundfos_DHWAsync();
        }
        
        public string ConnectBeckett() {
            return base.Channel.ConnectBeckett();
        }
        
        public System.Threading.Tasks.Task<string> ConnectBeckettAsync() {
            return base.Channel.ConnectBeckettAsync();
        }
        
        public string ConnectNorthInvent() {
            return base.Channel.ConnectNorthInvent();
        }
        
        public System.Threading.Tasks.Task<string> ConnectNorthInventAsync() {
            return base.Channel.ConnectNorthInventAsync();
        }
        
        public string ConnectWIonline() {
            return base.Channel.ConnectWIonline();
        }
        
        public System.Threading.Tasks.Task<string> ConnectWIonlineAsync() {
            return base.Channel.ConnectWIonlineAsync();
        }
        
        public string ConnectAscomSPC() {
            return base.Channel.ConnectAscomSPC();
        }
        
        public System.Threading.Tasks.Task<string> ConnectAscomSPCAsync() {
            return base.Channel.ConnectAscomSPCAsync();
        }
        
        public string ConnectCostapprovalMTH() {
            return base.Channel.ConnectCostapprovalMTH();
        }
        
        public System.Threading.Tasks.Task<string> ConnectCostapprovalMTHAsync() {
            return base.Channel.ConnectCostapprovalMTHAsync();
        }
        
        public string ConnectITax() {
            return base.Channel.ConnectITax();
        }
        
        public System.Threading.Tasks.Task<string> ConnectITaxAsync() {
            return base.Channel.ConnectITaxAsync();
        }
        
        public string GetdatTimeYYYY_MM_DD() {
            return base.Channel.GetdatTimeYYYY_MM_DD();
        }
        
        public System.Threading.Tasks.Task<string> GetdatTimeYYYY_MM_DDAsync() {
            return base.Channel.GetdatTimeYYYY_MM_DDAsync();
        }
        
        public string ConnectSFRdatabase() {
            return base.Channel.ConnectSFRdatabase();
        }
        
        public System.Threading.Tasks.Task<string> ConnectSFRdatabaseAsync() {
            return base.Channel.ConnectSFRdatabaseAsync();
        }
        
        public string ConnectRFQdatabase() {
            return base.Channel.ConnectRFQdatabase();
        }
        
        public System.Threading.Tasks.Task<string> ConnectRFQdatabaseAsync() {
            return base.Channel.ConnectRFQdatabaseAsync();
        }
        
        public string ConnectPTDMTH() {
            return base.Channel.ConnectPTDMTH();
        }
        
        public System.Threading.Tasks.Task<string> ConnectPTDMTHAsync() {
            return base.Channel.ConnectPTDMTHAsync();
        }
        
        public string ConnectSamvac() {
            return base.Channel.ConnectSamvac();
        }
        
        public System.Threading.Tasks.Task<string> ConnectSamvacAsync() {
            return base.Channel.ConnectSamvacAsync();
        }
        
        public string ConnectLabelsystem() {
            return base.Channel.ConnectLabelsystem();
        }
        
        public System.Threading.Tasks.Task<string> ConnectLabelsystemAsync() {
            return base.Channel.ConnectLabelsystemAsync();
        }
        
        public string ConnectPRdatabase() {
            return base.Channel.ConnectPRdatabase();
        }
        
        public System.Threading.Tasks.Task<string> ConnectPRdatabaseAsync() {
            return base.Channel.ConnectPRdatabaseAsync();
        }
        
        public string ConnectLattec() {
            return base.Channel.ConnectLattec();
        }
        
        public System.Threading.Tasks.Task<string> ConnectLattecAsync() {
            return base.Channel.ConnectLattecAsync();
        }
        
        public string ConnectRFQMTHdatabase() {
            return base.Channel.ConnectRFQMTHdatabase();
        }
        
        public System.Threading.Tasks.Task<string> ConnectRFQMTHdatabaseAsync() {
            return base.Channel.ConnectRFQMTHdatabaseAsync();
        }
        
        public string ConnectGambro() {
            return base.Channel.ConnectGambro();
        }
        
        public System.Threading.Tasks.Task<string> ConnectGambroAsync() {
            return base.Channel.ConnectGambroAsync();
        }
        
        public string ConnectHormann() {
            return base.Channel.ConnectHormann();
        }
        
        public System.Threading.Tasks.Task<string> ConnectHormannAsync() {
            return base.Channel.ConnectHormannAsync();
        }
        
        public string GetworkweekISO8601YYWww() {
            return base.Channel.GetworkweekISO8601YYWww();
        }
        
        public System.Threading.Tasks.Task<string> GetworkweekISO8601YYWwwAsync() {
            return base.Channel.GetworkweekISO8601YYWwwAsync();
        }
        
        public string GETworkweekISO8601WWYY() {
            return base.Channel.GETworkweekISO8601WWYY();
        }
        
        public System.Threading.Tasks.Task<string> GETworkweekISO8601WWYYAsync() {
            return base.Channel.GETworkweekISO8601WWYYAsync();
        }
        
        public string ConnectElero() {
            return base.Channel.ConnectElero();
        }
        
        public System.Threading.Tasks.Task<string> ConnectEleroAsync() {
            return base.Channel.ConnectEleroAsync();
        }
        
        public string ConnectBesi() {
            return base.Channel.ConnectBesi();
        }
        
        public System.Threading.Tasks.Task<string> ConnectBesiAsync() {
            return base.Channel.ConnectBesiAsync();
        }
        
        public string ConnectFlyingprobe() {
            return base.Channel.ConnectFlyingprobe();
        }
        
        public System.Threading.Tasks.Task<string> ConnectFlyingprobeAsync() {
            return base.Channel.ConnectFlyingprobeAsync();
        }
        
        public string ConnectEndress() {
            return base.Channel.ConnectEndress();
        }
        
        public System.Threading.Tasks.Task<string> ConnectEndressAsync() {
            return base.Channel.ConnectEndressAsync();
        }
        
        public string ConnectSMTSchedule() {
            return base.Channel.ConnectSMTSchedule();
        }
        
        public System.Threading.Tasks.Task<string> ConnectSMTScheduleAsync() {
            return base.Channel.ConnectSMTScheduleAsync();
        }
        
        public string ConnectKPI() {
            return base.Channel.ConnectKPI();
        }
        
        public System.Threading.Tasks.Task<string> ConnectKPIAsync() {
            return base.Channel.ConnectKPIAsync();
        }
        
        public string ConnectQCrdserver() {
            return base.Channel.ConnectQCrdserver();
        }
        
        public System.Threading.Tasks.Task<string> ConnectQCrdserverAsync() {
            return base.Channel.ConnectQCrdserverAsync();
        }
        
        public string ConnectTestStand_Diversity() {
            return base.Channel.ConnectTestStand_Diversity();
        }
        
        public System.Threading.Tasks.Task<string> ConnectTestStand_DiversityAsync() {
            return base.Channel.ConnectTestStand_DiversityAsync();
        }
        
        public string GetemailbyAccountname(string accountname) {
            return base.Channel.GetemailbyAccountname(accountname);
        }
        
        public System.Threading.Tasks.Task<string> GetemailbyAccountnameAsync(string accountname) {
            return base.Channel.GetemailbyAccountnameAsync(accountname);
        }
        
        public string GetemailbyEmployeeID(string employeeID) {
            return base.Channel.GetemailbyEmployeeID(employeeID);
        }
        
        public System.Threading.Tasks.Task<string> GetemailbyEmployeeIDAsync(string employeeID) {
            return base.Channel.GetemailbyEmployeeIDAsync(employeeID);
        }
        
        public string GETworkweekISO8601YYWW() {
            return base.Channel.GETworkweekISO8601YYWW();
        }
        
        public System.Threading.Tasks.Task<string> GETworkweekISO8601YYWWAsync() {
            return base.Channel.GETworkweekISO8601YYWWAsync();
        }
        
        public string ConnectFlowserve() {
            return base.Channel.ConnectFlowserve();
        }
        
        public System.Threading.Tasks.Task<string> ConnectFlowserveAsync() {
            return base.Channel.ConnectFlowserveAsync();
        }
        
        public string Connectftpascom() {
            return base.Channel.Connectftpascom();
        }
        
        public System.Threading.Tasks.Task<string> ConnectftpascomAsync() {
            return base.Channel.ConnectftpascomAsync();
        }
        
        public string GETworkweekISO8601WWSYYYY() {
            return base.Channel.GETworkweekISO8601WWSYYYY();
        }
        
        public System.Threading.Tasks.Task<string> GETworkweekISO8601WWSYYYYAsync() {
            return base.Channel.GETworkweekISO8601WWSYYYYAsync();
        }
        
        public System.Data.DataSet GetWIPbyworkorder(string Workorder) {
            return base.Channel.GetWIPbyworkorder(Workorder);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetWIPbyworkorderAsync(string Workorder) {
            return base.Channel.GetWIPbyworkorderAsync(Workorder);
        }
        
        public string ConnectTeledyne() {
            return base.Channel.ConnectTeledyne();
        }
        
        public System.Threading.Tasks.Task<string> ConnectTeledyneAsync() {
            return base.Channel.ConnectTeledyneAsync();
        }
        
        public string ConnectDieboldNixdorf() {
            return base.Channel.ConnectDieboldNixdorf();
        }
        
        public System.Threading.Tasks.Task<string> ConnectDieboldNixdorfAsync() {
            return base.Channel.ConnectDieboldNixdorfAsync();
        }
        
        public string ConnectSeisenbacher() {
            return base.Channel.ConnectSeisenbacher();
        }
        
        public System.Threading.Tasks.Task<string> ConnectSeisenbacherAsync() {
            return base.Channel.ConnectSeisenbacherAsync();
        }
        
        public string Convertemailfromlisttostring(string[] Emailteam) {
            return base.Channel.Convertemailfromlisttostring(Emailteam);
        }
        
        public System.Threading.Tasks.Task<string> ConvertemailfromlisttostringAsync(string[] Emailteam) {
            return base.Channel.ConvertemailfromlisttostringAsync(Emailteam);
        }
        
        public string Convertemailfromstring(string Emailteam) {
            return base.Channel.Convertemailfromstring(Emailteam);
        }
        
        public System.Threading.Tasks.Task<string> ConvertemailfromstringAsync(string Emailteam) {
            return base.Channel.ConvertemailfromstringAsync(Emailteam);
        }
        
        public string ConnectGavilar() {
            return base.Channel.ConnectGavilar();
        }
        
        public System.Threading.Tasks.Task<string> ConnectGavilarAsync() {
            return base.Channel.ConnectGavilarAsync();
        }
        
        public string ConnectWindowmasterCustomer() {
            return base.Channel.ConnectWindowmasterCustomer();
        }
        
        public System.Threading.Tasks.Task<string> ConnectWindowmasterCustomerAsync() {
            return base.Channel.ConnectWindowmasterCustomerAsync();
        }
        
        public string[] GetStart_EnddateofLastmonth() {
            return base.Channel.GetStart_EnddateofLastmonth();
        }
        
        public System.Threading.Tasks.Task<string[]> GetStart_EnddateofLastmonthAsync() {
            return base.Channel.GetStart_EnddateofLastmonthAsync();
        }
        
        public string ConnectDanfoss() {
            return base.Channel.ConnectDanfoss();
        }
        
        public System.Threading.Tasks.Task<string> ConnectDanfossAsync() {
            return base.Channel.ConnectDanfossAsync();
        }
        
        public string GetAccountNamebyEmail(string Email) {
            return base.Channel.GetAccountNamebyEmail(Email);
        }
        
        public System.Threading.Tasks.Task<string> GetAccountNamebyEmailAsync(string Email) {
            return base.Channel.GetAccountNamebyEmailAsync(Email);
        }
        
        public string Getdatedd_MM_yy() {
            return base.Channel.Getdatedd_MM_yy();
        }
        
        public System.Threading.Tasks.Task<string> Getdatedd_MM_yyAsync() {
            return base.Channel.Getdatedd_MM_yyAsync();
        }
        
        public string Getdateyyy_MM_dd() {
            return base.Channel.Getdateyyy_MM_dd();
        }
        
        public System.Threading.Tasks.Task<string> Getdateyyy_MM_ddAsync() {
            return base.Channel.Getdateyyy_MM_ddAsync();
        }
        
        public string Getdatedd_MM_yy_HHmmss() {
            return base.Channel.Getdatedd_MM_yy_HHmmss();
        }
        
        public System.Threading.Tasks.Task<string> Getdatedd_MM_yy_HHmmssAsync() {
            return base.Channel.Getdatedd_MM_yy_HHmmssAsync();
        }
        
        public string ConvertEmailDuplicate(string Email) {
            return base.Channel.ConvertEmailDuplicate(Email);
        }
        
        public System.Threading.Tasks.Task<string> ConvertEmailDuplicateAsync(string Email) {
            return base.Channel.ConvertEmailDuplicateAsync(Email);
        }
        
        public int GetWeekOfMonth(System.DateTime dateValue) {
            return base.Channel.GetWeekOfMonth(dateValue);
        }
        
        public System.Threading.Tasks.Task<int> GetWeekOfMonthAsync(System.DateTime dateValue) {
            return base.Channel.GetWeekOfMonthAsync(dateValue);
        }
        
        public string Removeemailfromgroup(string Emailall, string RemoveEmail) {
            return base.Channel.Removeemailfromgroup(Emailall, RemoveEmail);
        }
        
        public System.Threading.Tasks.Task<string> RemoveemailfromgroupAsync(string Emailall, string RemoveEmail) {
            return base.Channel.RemoveemailfromgroupAsync(Emailall, RemoveEmail);
        }
    }
}
